V =		2.4.2
SLANG =		rus
DLANG =		eng
DICT_NAME = 	full
HOMEPAGE =	https://sourceforge.net/projects/xdxf
MASTER_SITES =	https://downloads.sourceforge.net/xdxf/
DISTNAME=	stardict-comn_sdict05_rus_eng_full-${V}
EXTRACT_SUFX =	.tar.bz2
EXTRACT_NAME =  stardict-rus_eng_full-${V}

.include <bsd.port.mk>
