COMMENT =		speed control depends on CPU temperature
V =			0.1.0
PKGNAME =		fand-${V}
CATEGORIES =		sysutils
MAINTAINER =		Viacheslav Chimishuk <vchimishuk@yandex.ru>
HOMEPAGE =		https://github.com/vchimishuk/fand
GH_ACCOUNT =		vchimishuk
GH_PROJECT =		fand
GH_TAGNAME =		v${V}
PERMIT_PACKAGE =	Yes
COMPILER =		base-clang ports-gcc base-gcc

.include <bsd.port.mk>
