V =		2.4.2
SLANG =		eng
DLANG =		rus
DICT_NAME = 	idioms
HOMEPAGE =	https://sourceforge.net/projects/xdxf
SITES =		https://downloads.sourceforge.net/xdxf/
DISTNAME=	stardict-comn_sdict05_idioms_eng_rus-${V}
EXTRACT_SUFX =	.tar.bz2
EXTRACT_NAME =  stardict-idioms_eng_rus-${V}

.include <bsd.port.mk>
