V =		2.4.2
SLANG =		eng
DLANG =		rus
DICT_NAME = 	computer
HOMEPAGE =	https://sourceforge.net/projects/xdxf
SITES =		https://downloads.sourceforge.net/xdxf/
DISTNAME=	stardict-comn_sdict05_eng_rus_comp-${V}
EXTRACT_SUFX =	.tar.bz2
EXTRACT_NAME =  stardict-eng_rus_comp-${V}

.include <bsd.port.mk>
